spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipping
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL95Dialect
  jackson:
    default-property-inclusion: NON_NULL
